(()=>{'use strict';
 const lang=document.documentElement.lang,ru=lang==='ru',t=(a,b)=>ru?a:b,id=document.body.dataset.demo;
 const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
 const money=n=>new Intl.NumberFormat(ru?'ru-RU':'en-GB',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
 const invalidate=form=>{const out=form?.querySelector('.form-result');if(out)out.hidden=true;};
 const toast=message=>{const el=$('.toast');el.textContent=message;el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,2500)};
 const today=new Date();const iso=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
 const tomorrow=new Date(today.getFullYear(),today.getMonth(),today.getDate()+1);
 all('input[type=date]').forEach(input=>{input.min=iso(today);input.value=iso(tomorrow);const end=new Date(today.getFullYear(),today.getMonth()+3,today.getDate());input.max=iso(end)});
 const prettyDate=s=>new Intl.DateTimeFormat(ru?'ru-RU':'en-GB',{day:'numeric',month:'long'}).format(new Date(s+'T12:00:00'));
 const dialog=$('#detail');let opener,oldOverflow='';
 const open=(label,content,trigger)=>{opener=trigger;$('#detailLabel').textContent=label;$('#detailContent').innerHTML=content;oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';dialog.showModal();$('.dialog-close').focus();$('#detailContent').scrollTop=0};
 const close=()=>dialog.close();$('.dialog-close').addEventListener('click',close);dialog.addEventListener('close',()=>{document.body.style.overflow=oldOverflow;opener?.focus({preventScroll:true})});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close()}});
 function result(form,text){const out=form.querySelector('.form-result');out.replaceChildren();const p=document.createElement('p');p.textContent=text;out.append(p);const button=document.createElement('button');button.type='button';button.textContent=t('Изменить выбор','Change selection');button.addEventListener('click',()=>{out.hidden=true;form.querySelector('input,select').focus()});out.append(button);out.hidden=false;out.tabIndex=-1;out.focus({preventScroll:true});out.scrollIntoView({block:'nearest',behavior:'smooth'});}
 const plan=(rooms,large=false)=>{
  const label=(x,y,value)=>`<text x="${x}" y="${y}" fill="currentColor" text-anchor="middle" font-family="Arial" font-size="9">${value}</text>`;
  const partitions=rooms===0?'':rooms===1?'M158 22V68M158 85V93H258':rooms===2?'M122 22V69M122 86V94H258M190 22V94':'M100 22V68M100 85V93H258M153 22V93M205 22V93';
  const bedrooms=rooms===0?'':rooms===1?label(208,60,t('СПАЛЬНЯ','BEDROOM')):rooms===2?label(155,60,t('СПАЛЬНЯ 1','BEDROOM 1'))+label(224,60,t('СПАЛЬНЯ 2','BEDROOM 2')):[126,179,231].map((x,i)=>label(x,54,'0'+(i+1))+label(x,69,t('СПАЛЬНЯ','BEDROOM'))).join('');
  return `<svg class="plan" viewBox="0 0 280 190" role="img" aria-label="${rooms===0?t('Схема студии с открытой жилой зоной','Studio plan with an open living area'):t(`Схема квартиры: ${rooms} спальни`,`Schematic plan: ${rooms} bedrooms`)}" style="${large?'height:260px':''}" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M22 22H258V148H200V170H22Z" stroke="currentColor" stroke-width="3"/><path d="M22 94H65M82 94H90V170${partitions}" stroke="currentColor" stroke-width="2"/><path d="M38 22H72M210 22H242M22 112V142" stroke="#95c4bc" stroke-width="5"/><path d="M82 94A17 17 0 0 1 65 111V94" stroke="currentColor"/>${label(58,57,t('КУХНЯ','KITCHEN'))}${label(56,137,t('САНУЗЕЛ','BATH'))}${label(175,133,rooms===0?t('ЖИЛАЯ ЗОНА','OPEN LIVING'):t('ГОСТИНАЯ','LIVING'))}${bedrooms}</svg>`;
 };
 if(id==='forma'){
  const homes=[{id:'A-12',rooms:0,area:32,price:220000,floor:2,view:t('Во двор','Courtyard')},{id:'A-24',rooms:1,area:48,price:310000,floor:4,view:t('На сад','Garden')},{id:'B-08',rooms:1,area:56,price:365000,floor:2,view:t('На город','City')},{id:'B-32',rooms:2,area:74,price:480000,floor:5,view:t('Во двор','Courtyard')},{id:'C-16',rooms:2,area:86,price:590000,floor:3,view:t('На сад','Garden')},{id:'C-41',rooms:3,area:118,price:850000,floor:6,view:t('Терраса','Terrace')}];
  const key='miro-forma-favourites';let saved=[];try{const raw=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(raw))saved=raw.filter(x=>homes.some(h=>h.id===x));}catch{}
  let rooms='all';const bedroom=h=>h.rooms===0?t('Студия','Studio'):t(`${h.rooms} ${h.rooms===1?'спальня':h.rooms<5?'спальни':'спален'}`,`${h.rooms} bedroom${h.rooms===1?'':'s'}`);
  function render(){
   const selected=homes.filter(h=>(rooms==='all'||h.rooms===+rooms)&&h.price<=+$('#budget').value&&(!$('#savedOnly').checked||saved.includes(h.id)));
   $('#budgetLabel').textContent=money(+$('#budget').value);$('#homeCount').textContent=t(`Вариантов: ${selected.length} · интерактивный просмотр`,`Homes: ${selected.length} · interactive preview`);
   $('#homeGrid').innerHTML=selected.length?selected.map(h=>`<article class="home-card"><div class="home-card-head"><span>FORMA / ${h.id}</span><button type="button" class="save-home" data-save="${h.id}" aria-label="${t('Сохранить квартиру','Save apartment')} ${h.id}" aria-pressed="${saved.includes(h.id)}">${saved.includes(h.id)?'♥':'♡'}</button></div>${plan(h.rooms)}<h3>${bedroom(h)} · ${h.area} ${t('м²','m²')}</h3><small>${t('Этаж','Floor')} ${h.floor} / ${h.view}</small><div class="home-card-foot"><strong>${money(h.price)}</strong><button type="button" data-home="${h.id}">${t('Подробнее','Explore')} ↗</button></div></article>`).join(''):`<div class="empty-state"><p>${t('По этим условиям квартир нет. Попробуйте другой бюджет или количество спален.','No homes match these choices. Try another budget or bedroom count.')}</p><button class="button" type="button" id="resetHomes">${t('Сбросить фильтры','Reset filters')}</button></div>`;
  }
  all('[data-rooms]').forEach(b=>b.addEventListener('click',()=>{rooms=b.dataset.rooms;all('[data-rooms]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render()}));$('#budget').addEventListener('input',render);$('#savedOnly').addEventListener('change',render);
  $('#homeGrid').addEventListener('click',e=>{
   const save=e.target.closest('[data-save]');if(save){const value=save.dataset.save;saved=saved.includes(value)?saved.filter(x=>x!==value):[...saved,value];try{localStorage.setItem(key,JSON.stringify(saved))}catch{toast(t('Выбор сохранён только до закрытия страницы','Saved for this visit only'))}render();$(`[data-save="${value}"]`)?.focus({preventScroll:true});return;}
   if(e.target.closest('#resetHomes')){rooms='all';$('#budget').value=900000;$('#savedOnly').checked=false;all('[data-rooms]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.rooms==='all')));render();return;}
   const trigger=e.target.closest('[data-home]');if(!trigger)return;const h=homes.find(x=>x.id===trigger.dataset.home);
   open('FORMA / '+h.id,`<h2>${bedroom(h)}.<br>${h.area} ${t('м² для жизни','m² to call home')}.</h2>${plan(h.rooms,true)}<dl><div><dt>${t('Стоимость','Price')}</dt><dd>${money(h.price)}</dd></div><div><dt>${t('Этаж / вид','Floor / view')}</dt><dd>${h.floor} / ${h.view}</dd></div></dl><p class="form-note">${t('Просмотр проекта и схематичный план. Информация на этой странице портфолио не является офертой.','Project preview and schematic plan. Information on this portfolio page is not an offer of sale.')}</p><button class="button" type="button" data-enquire="${h.id}">${t('Запросить просмотр','Prepare a viewing')} ↗</button>`,trigger);
  });
  $('#enquiryHome').innerHTML=homes.map(h=>`<option value="${h.id}">${h.id} · ${bedroom(h)} · ${h.area} ${t('м²','m²')}</option>`).join('');
  $('#detailContent').addEventListener('click',e=>{const b=e.target.closest('[data-enquire]');if(b){$('#enquiryHome').value=b.dataset.enquire;invalidate($('#enquiryForm'));close();$('#enquire').scrollIntoView();$('#enquiryHome').focus({preventScroll:true})}});
  $('#enquiryForm').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;const h=homes.find(x=>x.id===$('#enquiryHome').value);result(form,t(`Выбор квартиры ${h.id} подготовлен. В этой локальной версии портфолио данные никуда не отправляются.`,`Apartment ${h.id} selected. This local portfolio preview does not send your details.`));});render();
 }
 if(id==='ember'){
  const dishes=[['01','small',true,['Томаты и буррата','Tomatoes & burrata'],['Спелые томаты, базилик, оливковое масло','Ripe tomatoes, basil, olive oil'],14,['Молоко','Milk']],['02','small',false,['Тартар из говядины','Beef tartare'],['Каперсы, горчица, хрустящий хлеб','Capers, mustard, crisp toast'],18,['Горчица, глютен, яйцо','Mustard, gluten, egg']],['03','small',true,['Печёные перцы','Roasted peppers'],['Миндальный крем, зелень, лимон','Almond cream, herbs, lemon'],12,['Орехи','Nuts']],['04','main',false,['Рыба на огне','Fish from the fire'],['Сезонные овощи, томаты, тёплый соус','Seasonal vegetables, tomatoes, warm sauce'],28,['Рыба, молоко','Fish, milk']],['05','main',true,['Грибное ризотто','Wild mushroom risotto'],['Пармезан, тимьян, белые грибы','Parmesan, thyme, wild mushrooms'],23,['Молоко','Milk']],['06','main',false,['Цыплёнок и лимон','Chicken & lemon'],['Картофель, розмарин, печёный чеснок','Potatoes, rosemary, roast garlic'],26,['Молоко','Milk']],['07','sweet',true,['Шоколадный тарт','Chocolate tart'],['Тёмный шоколад, морская соль','Dark chocolate, sea salt'],10,['Молоко, глютен, яйцо','Milk, gluten, egg']],['08','sweet',true,['Груша и ваниль','Pear & vanilla'],['Томлёная груша, ванильный крем','Poached pear, vanilla cream'],9,['Молоко','Milk']]];
  let category='all';const word=a=>a[ru?0:1];
  function render(){const rows=dishes.filter(d=>(category==='all'||d[1]===category)&&(!$('#vegetarian').checked||d[2]));$('#menuList').innerHTML=rows.map(d=>`<button class="dish" type="button" data-dish="${d[0]}"><span class="dish-number">${d[0]}</span><div><h3>${word(d[3])}</h3><p>${word(d[4])}</p></div><strong>€${d[5]}</strong></button>`).join('');$('#menuCount').textContent=t(`Блюд: ${rows.length} · цены в презентации проекта`,`Dishes: ${rows.length} · pricing shown in this project presentation`);}
  all('[data-category]').forEach(b=>b.addEventListener('click',()=>{category=b.dataset.category;all('[data-category]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render()}));$('#vegetarian').addEventListener('change',render);$('#menuList').addEventListener('click',e=>{const b=e.target.closest('[data-dish]');if(!b)return;const d=dishes.find(x=>x[0]===b.dataset.dish);open('EMBER / '+t('МЕНЮ','MENU'),`<h2>${word(d[3])}</h2><p>${word(d[4])}.</p><dl><div><dt>${t('Стоимость','Price')}</dt><dd>€${d[5]}</dd></div><div><dt>${t('Аллергены','Allergens')}</dt><dd>${word(d[6])}</dd></div></dl><p class="form-note">${t('Меню показано в презентации проекта. Перед заказом уточните актуальный состав и аллергены у команды ресторана.','Menu shown in the project presentation. Confirm current ingredients and allergens with the restaurant team before ordering.')}</p>`,b)});
  const tableForm=$('#tableForm'),tableDate=tableForm.elements.date,tableTime=tableForm.elements.time;
  const availableTables=()=>{const now=new Date();return tableDate.value&&tableDate.validity.valid?['12:00','13:30','18:00','19:30','21:00'].filter(v=>new Date(tableDate.value+'T'+v)>now):[]};
  function tableTimes(){invalidate(tableForm);const previous=tableTime.value,slots=availableTables();tableTime.innerHTML=slots.length?slots.map(v=>`<option>${v}</option>`).join(''):`<option value="">${t('Выберите другую дату','Choose another date')}</option>`;if(slots.includes(previous))tableTime.value=previous;tableTime.disabled=!slots.length;tableForm.querySelector('[type=submit]').disabled=!slots.length;}
  tableDate.addEventListener('change',tableTimes);
  tableForm.addEventListener('submit',e=>{e.preventDefault();if(!availableTables().includes(tableTime.value)){tableTimes();return;}const data=new FormData(tableForm);result(tableForm,t(`Ваш выбор: ${prettyDate(data.get('date'))}, ${data.get('time')}, гостей — ${data.get('guests')}. Эта версия портфолио не бронирует стол и не отправляет данные.`,`Your selection: ${prettyDate(data.get('date'))}, ${data.get('time')}, ${data.get('guests')} guest(s). This portfolio preview does not reserve a table or send your details.`));});tableTimes();render();
 }
 if(id==='line'){
  const services=[{id:'cut',ru:'Стрижка и укладка',en:'Cut & finish',minutes:60,price:65,staff:['anna','mia']},{id:'colour',ru:'Окрашивание',en:'Colour',minutes:120,price:120,staff:['anna','mia']},{id:'care',ru:'Уход для волос',en:'Hair treatment',minutes:45,price:45,staff:['anna','mia']},{id:'barber',ru:'Мужская стрижка',en:'Barber cut',minutes:45,price:40,staff:['leo']},{id:'brows',ru:'Форма бровей',en:'Brow shape',minutes:30,price:25,staff:['mia']},{id:'consult',ru:'Консультация',en:'Consultation',minutes:20,price:0,staff:['anna','mia','leo']}];
  const names={anna:'Anna',mia:'Mia',leo:'Leo'};let time='';
  $('#serviceList').innerHTML=services.map((s,i)=>`<button type="button" class="service-row" data-service-id="${s.id}"><span class="eyebrow">0${i+1}</span><h3>${s[lang]}</h3><span class="service-time">${s.minutes} ${t('мин','min')}</span><span class="service-price">${s.price?money(s.price):t('Бесплатно','No charge')}</span><span class="service-arrow" aria-hidden="true">↗</span></button>`).join('');$('#bookingService').innerHTML=services.map(s=>`<option value="${s.id}">${s[lang]}</option>`).join('');
  const chosen=()=>services.find(x=>x.id===$('#bookingService').value);
  const dayInput=$('#salonForm input[type=date]');
  function updateSummary(){const s=chosen();$('#salonSummary').textContent=`${s[lang]} / ${s.minutes} ${t('мин','min')} / ${money(s.price)}${time?' / '+time:''}`;$('#salonForm button[type=submit]').disabled=!time;}
  function availableTimes(){if(!dayInput.value||!dayInput.validity.valid)return [];const s=chosen(),date=new Date(dayInput.value+'T12:00:00'),now=new Date();return ['10:00','11:30','14:00','15:30','17:00'].filter((v,i)=>{const start=+v.slice(0,2)*60 + +v.slice(3);return date.getDay()!==0&&start+s.minutes<=18*60&&i!==(date.getDate()+Object.keys(names).indexOf($('#bookingStylist').value))%5&&new Date(dayInput.value+'T'+v).getTime()>now.getTime()+30*60000});}
  function times(){invalidate($('#salonForm'));const slots=availableTimes();
   time='';$('#salonTimes').innerHTML=slots.length?slots.map(v=>`<button type="button" data-time="${v}" aria-pressed="false">${v}</button>`).join(''):`<p>${t('На этот день свободного времени нет. Выберите другую дату.','No times in the preview schedule for this day. Choose another date.')}</p>`;updateSummary();}
  function staff(){const s=chosen(),prev=$('#bookingStylist').value;$('#bookingStylist').innerHTML=s.staff.map(x=>`<option value="${x}">${names[x]}</option>`).join('');if(s.staff.includes(prev))$('#bookingStylist').value=prev;times();}
  $('#bookingService').addEventListener('change',staff);$('#bookingStylist').addEventListener('change',times);dayInput.addEventListener('change',times);$('#salonTimes').addEventListener('click',e=>{const b=e.target.closest('[data-time]');if(!b)return;invalidate($('#salonForm'));time=b.dataset.time;all('[data-time]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));updateSummary()});
  $('#serviceList').addEventListener('click',e=>{const b=e.target.closest('[data-service-id]');if(b){$('#bookingService').value=b.dataset.serviceId;staff();$('#book').scrollIntoView();$('#bookingService').focus({preventScroll:true})}});
  $('#salonForm').addEventListener('submit',e=>{e.preventDefault();if(!availableTimes().includes(time)){times();return;}const s=chosen();result(e.currentTarget,t(`Ваш выбор: ${s.ru}, ${names[$('#bookingStylist').value]}, ${prettyDate(dayInput.value)} в ${time}. Стоимость ${money(s.price)}. Эта версия портфолио не создаёт запись и не отправляет данные.`,`Your selection: ${s.en}, ${names[$('#bookingStylist').value]}, ${prettyDate(dayInput.value)} at ${time}. ${money(s.price)}. This portfolio preview does not create an appointment or send your details.`));});staff();
 }
 // Sample choices must be reviewed again after the underlying inputs change.
 all('form').forEach(form=>{form.addEventListener('input',()=>invalidate(form));form.addEventListener('change',()=>invalidate(form));});
 all('.demo-fields').forEach(fieldset=>fieldset.disabled=false);
 if('IntersectionObserver'in window&&!matchMedia('(prefers-reduced-motion:reduce)').matches){document.documentElement.classList.add('has-motion');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});all('.reveal').forEach(e=>observer.observe(e));}
})();
